Remove HMAC
anybrain/curlinho pull request #14
Opened 2021-06-17 13:05 UTC by rruipinheiro

2021-06-18 09:44 UTC, serafimpinto approved these changes

2021-06-18 10:19 UTC, serafimpinto requested changes
It is missing remove the HMAC info from README

2021-06-18 15:34 UTC, serafimpinto approved these changes

2021-06-29 10:36 UTC, jlsilva1994 approved these changes

2021-06-29 16:39 UTC, merged